name: Upload PyTest cache

description: Uploads the pytest cache to S3

inputs:
  pr-identifier:
    description: Unique identifier that only repeats when the same workflow is being run against the same PR
    required: true

outputs:
  pr-identifier:
    description: "Processed identifier"
    value: ${{ steps.get-id.pr-identifier }}

runs:
  using: composite
  steps:
    - name: Get the S3 key
      id: get-id
      shell: bash
      env:
        PR_IDENTIFIER: ${{ inputs.pr-identifier }}
      run: |
        python -c 'import hashlib; import os; i = hashlib.md5(os.getenv("PR_IDENTIFIER").encode()).hexdigest(); print(f"::set-output name=pr-identifier::{i}")'