name: A zain test

on:
  push:
    # branches:
    #   - zainr/*
    tags:
      - ciflow/trunk/*
  workflow_dispatch:


jobs:
  check-events-here:
    name: github-events
    runs-on: linux.2xlarge
    env:
      PR_NUMBER: ${{ github.event.number }}
      EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}
      THE_REST: "${{ github.event.pull_requests }}"
      GH_SHA: ${{ github.sha }}
      GH_REF: ${{ github.ref_name }}
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main

      # invoke the upload-pytest-cache github action
      
      - name: Get workflow job id
        id: upload-pytest-cache
        uses: ./.github/actions/upload-pytest-cache
        with:
          github-token: ${GITHUB_REF}

      - name: Get output from action
        run: |
          echo ${{ steps.upload-pytest-cache.outputs.pr-identifier }}

      - name: "print GH_REF"
        run: |
          echo ${GH_REF}
          echo ${GITHUB_REF}
      - name: "print PR_NUMBER"
        run: |
          echo ${PR_NUMBER}
      - name: "print GH_SHA"
        run: |
          echo ${GH_SHA}
      - name: "print EVENT_PR_NUMBER"
        run: |
          echo ${EVENT_PR_NUMBER}
      - name: "print THE_REST"
        run: |
          echo ${THE_REST}