name: A zain test

on:
  push:
    tags:
      - ciflow/trunk/*
  workflow_dispatch:


jobs:
  check-events-here:
    name: github-events
    runs-on: linux.2xlarge
    env:
      PR_NUMBER: ${{ github.event.number }}
      EVENT_PR_NUMBER: ${{ github.event.pull_request.number }}
      THE_REST: "${{ github.event.pull_requests }}"
      GH_SHA: ${{ github.sha }}
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main

      - name: "print stuff"
        run: |
          git tag --points-at ${GH_SHA}
      - name: "print more"
        run: |
          echo ${PR_NUMBER}
      - name: "print GH_SHA"
        run: |
          echo ${GH_SHA}
      - name: "print EVENT_PR_NUMBER"
        run: |
          echo ${EVENT_PR_NUMBER}
      - name: "print and more"
        run: |
          echo ${THE_REST}